name: Upload Travel Data to S3

on:
  push:
    paths:
      - 'data/sample/*.csv'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload all sample CSV files to S3
        run: |
          year=$(date +"%Y")
          month=$(date +"%m")
          day=$(date +"%d")

          for file in data/sample/*.csv; do

            filename=$(basename "$file")

            aws s3 cp "$file" \
              "s3://travel-etl-project/raw/travel/year=${year}/month=${month}/day=${day}/${filename}"

          done