name: Upload Travel Data to S3

on:
  push:
    paths:
      - 'data/sample/**'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload File to S3
        run: |
          TIMESTAMP=$(date +"%Y%m%d_%H%M")

          aws s3 cp data/sample/travel_sample.csv \
          s3://travel-etl-project/raw/travel/year=2026/month=03/day=28/travel_${TIMESTAMP}.csv